const errorTypes = {
  INVALID_TRIANGLE_SIDES: 'INVALID_TRIANGLE_SIDES',
  INPUT_EMPTY_LENGTH: 'INPUT_EMPTY_LENGTH',
  FORM_EMPTY_LENGTH: 'FORM_EMPTY_LENGTH',
  INPUT_ZERO_OR_NEGATIVE_LENGTH: 'INPUT_ZERO_OR_NEGATIVE_LENGTH',
  FORM_ZERO_OR_NEGATIVE_LENGTH: 'FORM_ZERO_OR_NEGATIVE_LENGTH'
};

export default errorTypes;